Examples for Schemas
NoRedInk/json-elm-schema pull request #24
Opened 2017-07-12 12:25 UTC by jatinderjit

This is with reference to #23 - examples for schemas.

Does this work for you?

2017-07-15 11:38 UTC, amitu commented
Hey @jwoudenberg, when you have free time, can you please help us get this merged/released? @jatinderjit is a little stuck with testing part.

2017-07-15 18:03 UTC, jwoudenberg requested changes
Sorry for the delay in reviewing, this looks great! I've got one request for a change and then this is perfect to merge!

2017-07-15 18:03 UTC, jwoudenberg commented on src/JsonSchema/Model.elm
> +        , examples : Maybe (List Encode.Value)
Can we make this a simple list instead of a list wrapped in a maybe? The list being empty should be enough indication that there are no examples.

2017-07-15 18:05 UTC, jwoudenberg commented on cli/index.js
> +      $ elm-json-schema <elm-schema-file>
😻 Thanks for finding this and fixing!

2017-07-17 05:53 UTC, jatinderjit commented on src/JsonSchema/Model.elm
> +        , examples : Maybe (List Encode.Value)
Yes, that'd be better. On it.

2017-07-17 19:47 UTC, jatinderjit commented
@jwoudenberg unwrapped the examples from Maybe.

2017-07-17 20:37 UTC, jwoudenberg approved these changes
Awesome, thanks for contributing this!

2017-07-17 20:37 UTC, jwoudenberg commented on src/JsonSchema/Encoder.elm
> +        Just ( "examples", Encode.list examples )
Thanks for considering this case!

2017-07-17 20:37 UTC, merged

2017-07-17 20:38 UTC, jwoudenberg commented
Published as 2.2.0

2018-03-26 12:10 UTC, norpan commented
It seems to lack test cases